#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_arkher = env_modules.Clone()

# Arkher source files
env_arkher.add_source_files(env.modules_sources, "*.cpp")
